# Generated by Django 4.0.5 on 2022-06-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
