# Generated by Django 4.0.5 on 2022-06-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0003_alter_fotos_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição', verbose_name='Descrição'),
        ),
    ]
