# Generated by Django 4.0.5 on 2022-09-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imobiliaria', '0004_alter_fotos_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotos',
            name='foto',
            field=models.ImageField(blank=True, help_text='Escolha uma foto.', upload_to='fotosImoveis/%Y-%m-%d', verbose_name='Foto'),
        ),
    ]
